data: /waste-classification/data/waste-classification
model_dir: /waste-classification/models/waste-classification
arch: resnet18
resolution: 224
workers: 2
epochs: 35
start_epoch: 0
batch_size: 8
lr: 0.1
momentum: 0.9
weight_decay: 1e-4
print_freq: 10
resume: null
evaluate: true
pretrained: true
world_size: -1
rank: -1
dist_url: tcp://224.66.41.62:23456
dist_backend: nccl
seed: null
gpu: 0
multiprocessing_distributed: false
